name: CI Pipleline

on:
  push:
    branches: [main]

jobs:
  build:
    run-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: set up Node.js
      uses: actions/set-up-node@v3
      with:
          node-version: 16
        
    - name: Install dependencies
      run: npm Install

    - name: Run tests
      run: npm test
